const optionReligion = [
    { label: "12 Tribes of Israel", value: "12 Tribes of Israel" },
    { label: "Aglipayan", value: "Aglipayan" },
    { label: "Alliance", value: "Alliance" },
    { label: "Assembly of God", value: "Assembly of God" },
    { label: "Baptist", value: "Baptist" },
    { label: "Bible Baptist", value: "Bible Baptist" },
    { label: "Bible Based Christian", value: "Bible Based Christian" },
    { label: "Bible Believers", value: "Bible Believers" },
    { label: "Born Again Christian", value: "Born Again Christian" },
    { label: "Buddhism", value: "Buddhism" },
    { label: "Christ Believer", value: "Christ Believer" },
    { label: "Christ Faith Fellowship", value: "Christ Faith Fellowship" },
    { label: "Christian", value: "Christian" },
    { label: "Christianity", value: "Christianity" },
    { label: "Church of Christ", value: "Church of Christ" },
    { label: "Church of God", value: "Church of God" },
    { label: "Evangelical", value: "Evangelical" },
    { label: "Evangelical (Assemblies of God)", value: "Evangelical (Assemblies of God)" },
    { label: "Evangelical Christian", value: "Evangelical Christian" },
    { label: "Free Methodist", value: "Free Methodist" },
    { label: "Foursquare Gospel Church", value: "Foursquare Gospel Church" },
    { label: "Fundamental Baptist", value: "Fundamental Baptist" },
    { label: "Iglesia Filipina Independiente", value: "Iglesia Filipina Independiente" },
    { label: "Iglesia ni Cristo", value: "Iglesia ni Cristo" },
    { label: "Islam", value: "Islam" },
    { label: "Jehovah's Witness", value: "Jehovah's Witness" },
    { label: "Jesus is Lord", value: "Jesus is Lord" },
    { label: "Jesus Miracle Crusade", value: "Jesus Miracle Crusade" },
    { label: "Latter Day Saints", value: "Latter Day Saints" },
    { label: "MECA", value: "MECA" },
    { label: "Members Church of God International", value: "Members Church of God International" },
    { label: "Missionary Baptist", value: "Missionary Baptist" },
    { label: "Moncadista", value: "Moncadista" },
    { label: "Mormon", value: "Mormon" },
    { label: "New Apostolic", value: "New Apostolic" },
    { label: "New Day Captive Ministry, Int.", value: "New Day Captive Ministry, Int." },
    { label: "New Testament", value: "New Testament" },
    { label: "P.D.A. Church", value: "P.D.A. Church" },
    { label: "PECC", value: "PECC" },
    { label: "PECCAVI", value: "PECCAVI" },
    { label: "PEGAMI", value: "PEGAMI" },
    { label: "Pentecostal", value: "Pentecostal" },
    { label: "Philcan Christian Alliance", value: "Philcan Christian Alliance" },
    { label: "Philippine Independent Catholic", value: "Philippine Independent Catholic" },
    { label: "Philippine Independent Church", value: "Philippine Independent Church" },
    { label: "Pilinista", value: "Pilinista" },
    { label: "Protestant", value: "Protestant" },
    { label: "Reality of Christ", value: "Reality of Christ" },
    { label: "Roman Catholic", value: "Roman Catholic" },
    { label: "Seventh Day Adventist", value: "Seventh Day Adventist" },
    { label: "Sikh", value: "Sikh" },
    { label: "Sovereign Grace Life Church", value: "Sovereign Grace Life Church" },
    { label: "The Church of Jesus Of Latter Day Saints", value: "The Church of Jesus Of Latter Day Saints" },
    { label: "UCCP", value: "UCCP" },
    { label: "UCCP-Protestant", value: "UCCP-Protestant" },
];
export default optionReligion;
